language: php
php:
    - 7.2
    - nightly
before_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then EXTENSIONDIR=`php -r 'echo ini_get("extension_dir");'` && sed -i.bak 's/xdebug.max_nesting_level=256/xdebug.max_nesting_level=600/' ${EXTENSIONDIR}/xdebug.so; fi
    - composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
