language: php
php:
    - 7.2
    - nightly
before_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then sed -i.bak 's/xdebug.max_nesting_level=256/xdebug.max_nesting_level=600/' ~/.phpenv/versions/$(phpenv version-name)/etc/xdebug.ini; fi
    - composer install
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
